apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  - name: httpd
    image: httpd
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/local/apache2/htdocs
