apiVersion: v1
kind: Pod
metadata:
  name: sqlite-pod
spec:
  containers:
  - name: sqlite-container
    image: sqlite
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: dbsecret
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dbsecret
            key: password
